# name: Deploy Frontend to Docker Hub and Server

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build-and-deploy-frontend:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: Set up Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: 18

#     - name: Build frontend Docker image
#       run: |
#         docker build \
#           --build-arg REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }} \
#           -t emiruuzun/test-project-frontend:latest .

#     - name: Log in to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     - name: Push frontend Docker image to Docker Hub
#       run: |
#         docker push emiruuzun/test-project-frontend:latest

#     - name: SSH into server and deploy
#       uses: appleboy/ssh-action@v0.1.7
#       with:
#         host: ${{ secrets.SERVER_HOST }}
#         username: ${{ secrets.SERVER_USER }}
#         key: ${{ secrets.SERVER_SSH_KEY }}
#         port: ${{ secrets.SERVER_PORT }}
#         script: |
#           cd /home/ubuntu/myTestProject
#           sudo docker compose down
#           sudo docker ps -a -q --filter "name=nginx" | grep . && sudo docker rm -f $(sudo docker ps -a -q --filter "name=nginx") || true
#           sudo docker ps -a -q --filter "name=frontend" | grep . && sudo docker rm -f $(sudo docker ps -a -q --filter "name=frontend") || true
#           sudo docker ps -a -q --filter "name=backend" | grep . && sudo docker rm -f $(sudo docker ps -a -q --filter "name=backend") || true
#           sudo docker ps -aq | grep . && sudo docker rm -f $(sudo docker ps -aq) || true
#           sudo docker images -q | grep . && sudo docker rmi $(sudo docker images -q) || true
#           sudo docker compose up -d --build



name: Deploy Frontend to Docker Hub and Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build frontend Docker image
      run: |
        docker build \
          --build-arg REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }} \
          --build-arg REACT_APP_SOCKET_URL=${{ secrets.REACT_APP_SOCKET_URL }} \
          -t emiruuzun/test-project-frontend:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push frontend Docker image to Docker Hub
      run: |
        docker push emiruuzun/test-project-frontend:latest

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /home/ubuntu/myTestProject
          sudo docker compose down --remove-orphans
          sudo docker compose up -d --build
